(() => {
  'use strict';
  const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
  const state = { config: null, contacts: [], manual: [], models: [], modelError: '', selectedPage: 'overview', recordTimer: null, statusTimer: null, memoryDirty: false, configDirty: false };
  const api = async (path, options = {}) => { const res = await fetch(path, { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); let data = null; try { data = await res.json(); } catch (_) {} if (!res.ok || data?.error) throw new Error(data?.error || `请求失败（${res.status}）`); return data; };
  const notice = (msg, error = false) => { const el = $('#notice'); el.textContent = msg; el.className = `notice ${error ? 'error' : 'success'}`; el.hidden = false; clearTimeout(notice.t); notice.t = setTimeout(() => { el.hidden = true; }, 4200); };
  const fmt = v => v ? new Date(v).toLocaleString('zh-CN', { hour12: false }) : '—';
  const escape = v => String(v ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  function navigate(page) { state.selectedPage = page; $$('.nav-item').forEach(b => b.classList.toggle('active', b.dataset.page === page)); $$('.page').forEach(p => p.classList.toggle('active', p.id === `page-${page}`)); if (page === 'records') loadRecords(); if (page === 'memory') loadMemory(); }
  $$('.nav-item').forEach(b => b.addEventListener('click', () => navigate(b.dataset.page)));
  function renderStatus(s) { if (!s) return; const running = s.running === true; $('#status-dot').className = `status-dot ${running ? 'on' : 'off'}`; $('#status-text').textContent = running ? '自动回复运行中' : '已暂停'; $('#status-detail').textContent = s.last_error ? `服务报告：${s.last_error}` : (running ? '本地脚本正在监测微信' : '启动后才会监测微信'); $('#toggle-running').textContent = running ? '暂停自动回复' : '启动自动回复'; $('#poll-value').textContent = Number.isFinite(s.poll_seconds) ? `${s.poll_seconds} 秒` : '—'; $('#reply-count').textContent = s.counts?.replies ?? '—'; $('#skip-count').textContent = s.counts?.skipped ?? '—'; $('#needs-count').textContent = s.counts?.needs_user ?? '—'; $('#last-scan').textContent = `最近扫描：${fmt(s.last_scan)}`; }
  async function loadStatus() { try { renderStatus(await api('/api/status')); } catch (e) { $('#status-dot').className = 'status-dot off'; $('#status-text').textContent = '服务不可达'; $('#status-detail').textContent = e.message; $('#toggle-running').disabled = true; } }
  $('#toggle-running').addEventListener('click', async () => { const running = $('#status-dot').classList.contains('on'); $('#toggle-running').disabled = true; try { renderStatus(await api('/api/control', { method: 'POST', body: JSON.stringify({ action: running ? 'stop' : 'start' }) })); notice(running ? '已暂停自动回复' : '已启动自动回复'); } catch (e) { notice(e.message, true); } finally { $('#toggle-running').disabled = false; } });
  function markConfigDirty() { state.configDirty = true; }
  function modelOptions(id) { const assigned = state.config?.contact_models?.[id]; const valid = state.models.some(m => m.id === assigned); const inherit = `<option value="">继承全局（${escape(state.config?.model || '当前模型')}）</option>`; const invalid = assigned && !valid ? `<option value="${escape(assigned)}" selected>无效模型：${escape(assigned)}（待重新选择）</option>` : ''; const options = state.models.map(m => `<option value="${escape(m.id)}" ${m.id === assigned ? 'selected' : ''}>${escape(m.label || m.id)}</option>`).join(''); return `<select class="contact-model" data-model-contact="${escape(id)}" aria-label="${escape('为联系人 ' + id + ' 选择模型')}">${assigned && valid ? '' : inherit}${invalid}${options}</select>`; }
  function renderContacts() { const q = $('#contact-search').value.trim().toLowerCase(); const all = [...state.contacts, ...state.manual.map(name => ({ id: name, name, kind: 'manual', last_seen: null }))]; const items = all.filter(c => !q || c.name.toLowerCase().includes(q)); $('#contacts-list').innerHTML = items.length ? items.map(c => { const system = c.kind === 'system'; const inc = state.config?.include?.includes(c.id); const ign = state.config?.ignore?.includes(c.id); return `<div class="contact-row ${system ? 'disabled' : ''}"><div><strong>${escape(c.name)}</strong><span class="contact-kind">${system ? '系统联系人 · 不可选' : c.kind === 'group' ? '群聊' : c.kind === 'manual' ? '手动' : '联系人'}${ign ? ' · 当前忽略' : ''}</span></div><div class="contact-actions"><label><input type="checkbox" data-contact="${escape(c.id)}" data-kind="include" ${inc ? 'checked' : ''} ${system ? 'disabled' : ''}> 回复</label><label><input type="checkbox" data-contact="${escape(c.id)}" data-kind="ignore" ${ign ? 'checked' : ''} ${system ? 'disabled' : ''}> 忽略</label>${!system && state.models.length ? modelOptions(c.id) : ''}</div></div>`; }).join('') : '<div class="empty">没有匹配的已发现联系人</div>'; $$('[data-contact]').forEach(i => i.addEventListener('change', () => { const id = i.dataset.contact; const key = i.dataset.kind; const other = key === 'include' ? 'ignore' : 'include'; if (!state.config[key]) state.config[key] = []; state.config[key] = i.checked ? [...new Set([...state.config[key], id])] : state.config[key].filter(x => x !== id); state.config[other] = (state.config[other] || []).filter(x => x !== id); renderContacts(); markConfigDirty(); })); $$('[data-model-contact]').forEach(s => s.addEventListener('change', () => { const id = s.dataset.modelContact; state.config.contact_models ||= {}; if (s.value) state.config.contact_models[id] = s.value; else delete state.config.contact_models[id]; markConfigDirty(); })); }
  function renderReplyMode() { const mode = $('input[name=reply-mode]:checked')?.value || 'model'; $('#reply-mode-label').textContent = `当前：${mode === 'template' ? '固定模板（零模型调用）' : 'Luna 按语境生成'}`; $('#mode-hint').textContent = mode === 'template' ? '自动回复使用模板；模板支持 {name} 和 {message}，不能为空。' : '使用模型结合来信、风格和上下文生成回复；已保存模板不会改变此模式。'; }
  function renderGlobalModel() { const select = $('#global-model'); const current = state.config?.model || ''; const valid = state.models.some(m => m.id === current); select.innerHTML = (current && !valid ? `<option value="${escape(current)}">无效模型：${escape(current)}（待重新选择）</option>` : '') + state.models.map(m => `<option value="${escape(m.id)}">${escape(m.label || m.id)}</option>`).join(''); select.value = valid ? current : (current || ''); select.disabled = !state.models.length; $('#models-error').hidden = !state.modelError; $('#models-error').textContent = state.modelError; $('#retry-models').hidden = !state.modelError; }
  async function loadModels() { try { const d = await api('/api/models'); state.models = d.models || []; state.modelError = state.models.length ? '' : '本地服务未提供可用模型'; renderGlobalModel(); renderContacts(); } catch (e) { state.models = []; state.modelError = e.message; renderGlobalModel(); $('#contacts-list').innerHTML = `<div class="empty">模型列表不可用：${escape(e.message)}，请在设置区重试</div>`; } }
  async function loadConfig() { try { state.config = await api('/api/config'); state.config.contact_models ||= {}; $('#group-mentions').checked = state.config.group_mentions_only !== false; $('#style').value = state.config.style || ''; $('#template').value = state.config.template || ''; $$('input[name=scope]').forEach(i => i.checked = i.value === (state.config.scope || 'all')); $$('input[name=reply-mode]').forEach(i => i.checked = i.value === (state.config.reply_mode || 'model')); renderReplyMode(); $('#poll-seconds').value = state.config.poll_seconds || 10; state.configDirty = false; renderGlobalModel(); renderContacts(); } catch (e) { notice(e.message, true); } }
  async function loadContacts() { try { const data = await api('/api/contacts'); state.contacts = data.contacts || []; renderContacts(); } catch (e) { $('#contacts-list').innerHTML = `<div class="empty">${escape(e.message)}</div>`; } }
  $('#contact-search').addEventListener('input', renderContacts); $('#refresh-contacts').addEventListener('click', async () => { const b = $('#refresh-contacts'); b.disabled = true; b.textContent = '读取中…'; try { const d = await api('/api/contacts/refresh', { method: 'POST', body: '{}' }); state.contacts = d.contacts || []; renderContacts(); notice('已从微信刷新联系人'); } catch (e) { notice(e.message, true); } finally { b.disabled = false; b.textContent = '从微信刷新'; } });
  $('#add-contact').addEventListener('click', () => { const input = $('#manual-contact'); const name = input.value.trim(); if (!name) return; if (!state.manual.includes(name)) state.manual.push(name); input.value = ''; renderContacts(); notice('已添加手动匹配名称'); });
  ['#style','#template','#group-mentions'].forEach(s => $(s).addEventListener('input', markConfigDirty)); $$('input[name=scope]').forEach(i => i.addEventListener('change', markConfigDirty)); $$('input[name=reply-mode]').forEach(i => i.addEventListener('change', () => { renderReplyMode(); markConfigDirty(); }));
  $('#save-config').addEventListener('click', async () => { const scope = $('input[name=scope]:checked')?.value || 'all'; const payload = { scope, include: state.config.include || [], ignore: state.config.ignore || [], group_mentions_only: $('#group-mentions').checked, poll_seconds: Math.min(3600, Math.max(3, Number($('#poll-seconds').value) || 10)), model: $('#global-model').value || state.config.model, contact_models: state.config.contact_models || {}, style: $('#style').value, template: $('#template').value, reply_mode: $('input[name=reply-mode]:checked')?.value || 'model', suffix: state.config.suffix || '（bot回复 beta）' }; try { state.config = await api('/api/config', { method:'PUT', body: JSON.stringify(payload) }); state.configDirty = false; renderReplyMode(); renderGlobalModel(); notice('回复配置已保存'); } catch (e) { notice(e.message, true); } });
  $('#generate-style').addEventListener('click', async () => { const ids = state.config?.include || []; const b = $('#generate-style'); b.disabled = true; b.textContent = '正在生成草稿…'; try { const d = await api('/api/style/generate', { method:'POST', body: JSON.stringify({ contact_ids: ids, sample_limit: 50 }) }); if (!state.configDirty && !$('#style').value && !$('#template').value) { $('#style').value = d.style || ''; $('#template').value = d.template || ''; } else { notice(`草稿已生成（${d.sample_count ?? 0} 条样本），为避免覆盖未保存编辑，请手动查看后填写`, false); return; } notice(`已生成草稿（${d.sample_count ?? 0} 条本人消息）`); } catch (e) { notice(e.message, true); } finally { b.disabled = false; b.textContent = '选聊天生成风格草稿'; } });
  function recordCard(r) { const status = r.status || 'unknown'; return `<article class="card record"><div class="record-top"><span>${escape(r.conversation || '未知会话')}</span><time>${escape(fmt(r.timestamp))}</time></div><div class="message incoming"><span class="message-label">来信</span><p>${escape(r.incoming)}</p></div><div class="message reply"><span class="message-label">回复</span><p>${escape(r.reply)}</p></div><div class="record-bottom"><span class="status-tag ${escape(status)}">${escape(status)}</span><span class="record-model">${escape(r.model || '—')}</span><div class="feedback"><button class="icon-btn ${r.feedback === 'good' ? 'selected' : ''}" data-rate="good" data-id="${escape(r.id)}" aria-label="回复有帮助">赞</button><button class="icon-btn ${r.feedback === 'bad' ? 'selected' : ''}" data-rate="bad" data-id="${escape(r.id)}" aria-label="回复有问题">问题</button></div></div><div class="feedback-form" data-form="${escape(r.id)}" hidden><label>纠正文本<textarea rows="2" data-correction></textarea></label><label class="check"><input type="checkbox" data-memory checked> 更新 Memory</label><button class="btn secondary" data-submit-feedback>提交反馈</button></div></article>`; }
  async function loadRecords() { try { const d = await api('/api/records?limit=100'); const list = d.records || []; $('#records-list').innerHTML = list.length ? list.map(recordCard).join('') : '<div class="empty">还没有回复记录</div>'; $$('#records-list [data-rate]').forEach(b => b.addEventListener('click', () => { const f = $(`[data-form="${CSS.escape(b.dataset.id)}"]`); f.hidden = false; f.dataset.rating = b.dataset.rate; f.querySelector('textarea').focus(); })); $$('#records-list [data-submit-feedback]').forEach(b => b.addEventListener('click', async () => { const f = b.closest('.feedback-form'); const id = f.dataset.form; b.disabled = true; try { await api(`/api/records/${encodeURIComponent(id)}/feedback`, { method:'POST', body: JSON.stringify({ rating: f.dataset.rating, correction: f.querySelector('[data-correction]').value, update_memory: f.querySelector('[data-memory]').checked }) }); notice('反馈已保存'); await loadRecords(); } catch(e) { notice(e.message, true); b.disabled = false; } })); } catch (e) { $('#records-list').innerHTML = `<div class="empty">${escape(e.message)} <button class="btn secondary" id="retry-records">重试</button></div>`; $('#retry-records')?.addEventListener('click', loadRecords); } }
  async function loadMemory() { if (state.memoryDirty) return; try { const d = await api('/api/memory'); $('#memory-content').value = d.content || ''; $('#memory-updated').textContent = `更新时间：${fmt(d.updated_at)}`; $('#memory-dirty').hidden = true; } catch (e) { notice(e.message, true); } }
  $('#memory-content').addEventListener('input', () => { state.memoryDirty = true; $('#memory-dirty').hidden = false; }); $('#save-memory').addEventListener('click', async () => { try { const d = await api('/api/memory', { method:'PUT', body: JSON.stringify({ content: $('#memory-content').value }) }); state.memoryDirty = false; $('#memory-dirty').hidden = true; $('#memory-updated').textContent = `更新时间：${fmt(d.updated_at)}`; notice('Memory 已保存'); } catch (e) { notice(e.message, true); } });
  async function loadSetup() { try { const d = await api('/api/setup'); $('#setup-url').textContent = d.dashboard_url ? `控制台：${d.dashboard_url}` : ''; $('#setup-list').innerHTML = (d.checks || []).map(c => `<div class="setup-row"><span class="check-icon ${c.ok === true ? 'ok' : c.ok === false ? 'bad' : 'unknown'}">${c.ok === true ? '✓' : c.ok === false ? '!' : '?'}</span><div><strong>${escape(c.label)}</strong><p>${escape(c.detail || '状态未知')}</p>${c.action_hint ? `<small>${escape(c.action_hint)}</small>` : ''}</div></div>`).join('') || '<div class="empty">暂无检查项</div>'; } catch (e) { $('#setup-list').innerHTML = `<div class="empty">${escape(e.message)} <button class="btn secondary" id="retry-setup">重试</button></div>`; $('#retry-setup')?.addEventListener('click', loadSetup); } }
  $('#global-model').addEventListener('change', () => { if (state.config) state.config.model = $('#global-model').value; markConfigDirty(); }); $('#retry-models').addEventListener('click', loadModels);
  $('#check-setup').addEventListener('click', async () => { const b = $('#check-setup'); b.disabled = true; b.textContent = '检查中…'; try { const d = await api('/api/setup/check', { method:'POST', body:'{}' }); $('#setup-url').textContent = d.dashboard_url ? `控制台：${d.dashboard_url}` : ''; await loadSetup(); notice('设置检查已完成'); } catch(e) { notice(e.message, true); } finally { b.disabled = false; b.textContent = '重新检查'; } });
  async function boot() { await Promise.all([loadStatus(), loadConfig(), loadContacts(), loadModels(), loadSetup()]); state.statusTimer = setInterval(loadStatus, 15000); state.recordTimer = setInterval(() => { if (state.selectedPage === 'records') loadRecords(); }, 15000); }
  boot();
})();
